In [7]:
import numpy as np
arr=np.array([12,35,57,77])
print(arr)
print(type(arr))

[12 35 57 77]
<class 'numpy.ndarray'>


In [10]:
#2d array
import numpy as np
arr=np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23]])
print(arr)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
