In [6]:
import pandas as pd 
import numpy as np

In [13]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target


In [18]:
print(len(X))

150


In [27]:
print(X.shape)
print(y.shape)
print(np.unique(y))
print(iris.target_names)


(150, 4)
(150,)
[0 1 2]
['setosa' 'versicolor' 'virginica']


In [31]:
def normalize(a):
    mu = np.mean(a, axis=0)      
    sigma = np.std(a, axis=0)     
    X_standardized = (a - mu) / sigma
    return X_standardized

print(normalize(X))

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [ ]:
from sklearn.preprocessing import OneHotEncoder

y = y.reshape(-1, 1)  
encoder = OneHotEncoder(sparse_output=False)
y_onehot = encoder.fit_transform(y)
print(y_onehot[:5])


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
# softmax 
def softmax(z):
    z = z - np.max( z , axis = 1, keepdims =True)
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z , axis =1 , keepdims =True)


# logits = np.array ([[2.0 , 1.0 , 0.1],[1.0 , 3.0 , 0.2]])

# probs = softmax(logits)
# print(probs)
# print( "row sum", probs.sum(axis=1))

[[0.65900114 0.24243297 0.09856589]
 [0.11314284 0.8360188  0.05083836]]
row sum [1. 1.]


In [ ]:
print()