In [7]:
import numpy as np
arr=np.array([12,35,57,77])
print(arr)
print(type(arr))

[12 35 57 77]
<class 'numpy.ndarray'>


In [10]:
#2d array
import numpy as np
arr=np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23]])
print(arr)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [1]:
import numpy as np 
a=np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [2]:
import numpy as np 
a=np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [3]:
import numpy as np 
a=np.array([[20,40],[60,80]])
print(np.append(a,90))

[20 40 60 80 90]


## NP.INSERT

In [4]:
import numpy as np
a=np.array([20,40,60,80])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [6]:
print(np.insert(a,1,88))

[20 88 40 60 80]


In [18]:
import numpy as np
a=np.array([[20,40],[60,80]])

In [19]:
print(np.insert(a,1,[50,60], axis=1))

[[20 50 40]
 [60 60 80]]


In [20]:
print(np.insert(a,1,[50,60],axis=0))

[[20 40]
 [50 60]
 [60 80]]


In [26]:
print(np.insert(a,[1,2],[50],axis=0))

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [2]:
import numpy as np
a=np.array([[20,40],[60,80]])

In [28]:
print(a)

[[20 40]
 [60 80]]


In [29]:
print(np.delete(a,1))

[20 60 80]


In [3]:
print(a)

[[20 40]
 [60 80]]


In [10]:
print(a)
print()
print(np.delete(a,1, axis =0))

[[20 40]
 [60 80]]

[[20 40]]


## sort 

In [12]:
import numpy as np
arr= np.array([[7,8,4,12,9],[2,8,5,1,2]])
print(np.sort(arr))

[[ 4  7  8  9 12]
 [ 1  2  2  5  8]]


## Search

In [13]:
arr=np.array([3,4,7,1,8])
s=np.where(arr == 4)
print(s)

(array([1]),)


In [21]:
arr=np.array([3,4,7,1,8])
s=np.where(arr %2==0)
print(s)


(array([1, 4]),)


## Filters

In [ ]:
arr =np.array([20,30,40,60])
fa=[True,False,True,False]
new=arr[fa]
print(new)

In [26]:
arr =np.array([20,30,40,60])
fa=[True,False,False,False]
new=arr[fa]
print(new)

[20]


In [29]:
arr =np.array([20,30,40,60])
fa=arr>35
new=arr[fa]
print(new)

[]


In [41]:
arr =np.array([2,3,4,6])
fa=arr%2==1
new=arr[fa]
print(new)

[3]


## agreagrate function in array

In [48]:
import numpy as np
a= np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

190
20
70
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [52]:
 a= [100,150,199,200,250,130]
b=[10,50,30,40,30,10]
price=np.array(a)
quantity=np.array(b)
print(price,"\n",quantity)
c=np.cumprod([price,quantity], axis =0)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
31270


## statistcical function in array

In [5]:
import numpy as np
import statistics as stats
bak_food= [200,300,150,130,200,280,170,188]
a= np.array(bak_food)
print(np.mean(bak_food))
print(np.median(bak_food))
print(stats.mode(bak_food))
print(np.std(bak_food))
print(np.var(bak_food))

202.25
194.0
200
55.68157235567257
3100.4375


In [9]:
toba_consum=[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]
print(np.corrcoef([toba_consum,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


## strongly negative values

In [10]:
#strongly negative values
price=[300,100,350,150,200]
sales=[10,20,7,17,3]

print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
